### ISSUE TITLE
Conflicting CSS

### ISSUE THREAD

**Issue by timbeccue** [ericmandel/js9#69]
Hi Eric,

My specific issue is that the js9 .control class style conflicts with another css library that I use. Changing js9.css to 
```css
.control {
    ...
    padding: 0px;  /* used to be 2px */
}
```
fixes the problem for me. But I had trouble finding the js9 components that use the .control class. Will this cause any issues?

In general, it looks like a lot of the class names are unique enough that maybe these conflicts are best addressed on an as-needed basis... though if there's an easy way to namespace all the classes, that might be a better permanent (albeit less readable) solution. What do you think?
